<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AvaloniaVersion>12.0.1</AvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.14" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="$(AvaloniaVersion)" />
    <!--For _build-->
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.102" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="11.4.12" />
  </ItemGroup>
</Project>